/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalibrationRouteImport } from './routes/calibration'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsCalibrationRouteImport } from './routes/settings.calibration'
import { Route as TokenTokenIdRouteImport } from './routes/token.$tokenId'
import { Route as ApiPublicOutcomeSamplerRouteImport } from './routes/api/public/outcome-sampler'
import { Route as ApiPublicProductionCycleTickRouteImport } from './routes/api/public/production-cycle-tick'
import { Route as ApiPublicThesisBenchmarkRouteImport } from './routes/api/public/thesis-benchmark'
import { Route as ApiPublicThesisV2CalibrationRouteImport } from './routes/api/public/thesis-v2-calibration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibrationRoute = CalibrationRouteImport.update({
  id: '/calibration',
  path: '/calibration',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCalibrationRoute = SettingsCalibrationRouteImport.update({
  id: '/calibration',
  path: '/calibration',
  getParentRoute: () => SettingsRoute,
} as any)
const TokenTokenIdRoute = TokenTokenIdRouteImport.update({
  id: '/token/$tokenId',
  path: '/token/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOutcomeSamplerRoute = ApiPublicOutcomeSamplerRouteImport.update({
  id: '/api/public/outcome-sampler',
  path: '/api/public/outcome-sampler',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductionCycleTickRoute =
  ApiPublicProductionCycleTickRouteImport.update({
    id: '/api/public/production-cycle-tick',
    path: '/api/public/production-cycle-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicThesisBenchmarkRoute =
  ApiPublicThesisBenchmarkRouteImport.update({
    id: '/api/public/thesis-benchmark',
    path: '/api/public/thesis-benchmark',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicThesisV2CalibrationRoute =
  ApiPublicThesisV2CalibrationRouteImport.update({
    id: '/api/public/thesis-v2-calibration',
    path: '/api/public/thesis-v2-calibration',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calibration': typeof CalibrationRoute
  '/history': typeof HistoryRoute
  '/research': typeof ResearchRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/settings/calibration': typeof SettingsCalibrationRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/public/outcome-sampler': typeof ApiPublicOutcomeSamplerRoute
  '/api/public/production-cycle-tick': typeof ApiPublicProductionCycleTickRoute
  '/api/public/thesis-benchmark': typeof ApiPublicThesisBenchmarkRoute
  '/api/public/thesis-v2-calibration': typeof ApiPublicThesisV2CalibrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calibration': typeof CalibrationRoute
  '/history': typeof HistoryRoute
  '/research': typeof ResearchRoute
  '/scanner': typeof ScannerRoute
  '/watchlist': typeof WatchlistRoute
  '/settings/calibration': typeof SettingsCalibrationRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
  '/settings': typeof SettingsIndexRoute
  '/api/public/outcome-sampler': typeof ApiPublicOutcomeSamplerRoute
  '/api/public/production-cycle-tick': typeof ApiPublicProductionCycleTickRoute
  '/api/public/thesis-benchmark': typeof ApiPublicThesisBenchmarkRoute
  '/api/public/thesis-v2-calibration': typeof ApiPublicThesisV2CalibrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calibration': typeof CalibrationRoute
  '/history': typeof HistoryRoute
  '/research': typeof ResearchRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/settings/calibration': typeof SettingsCalibrationRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/public/outcome-sampler': typeof ApiPublicOutcomeSamplerRoute
  '/api/public/production-cycle-tick': typeof ApiPublicProductionCycleTickRoute
  '/api/public/thesis-benchmark': typeof ApiPublicThesisBenchmarkRoute
  '/api/public/thesis-v2-calibration': typeof ApiPublicThesisV2CalibrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calibration'
    | '/history'
    | '/research'
    | '/scanner'
    | '/settings'
    | '/watchlist'
    | '/settings/calibration'
    | '/token/$tokenId'
    | '/settings/'
    | '/api/public/outcome-sampler'
    | '/api/public/production-cycle-tick'
    | '/api/public/thesis-benchmark'
    | '/api/public/thesis-v2-calibration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calibration'
    | '/history'
    | '/research'
    | '/scanner'
    | '/watchlist'
    | '/settings/calibration'
    | '/token/$tokenId'
    | '/settings'
    | '/api/public/outcome-sampler'
    | '/api/public/production-cycle-tick'
    | '/api/public/thesis-benchmark'
    | '/api/public/thesis-v2-calibration'
  id:
    | '__root__'
    | '/'
    | '/calibration'
    | '/history'
    | '/research'
    | '/scanner'
    | '/settings'
    | '/watchlist'
    | '/settings/calibration'
    | '/token/$tokenId'
    | '/settings/'
    | '/api/public/outcome-sampler'
    | '/api/public/production-cycle-tick'
    | '/api/public/thesis-benchmark'
    | '/api/public/thesis-v2-calibration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalibrationRoute: typeof CalibrationRoute
  HistoryRoute: typeof HistoryRoute
  ResearchRoute: typeof ResearchRoute
  ScannerRoute: typeof ScannerRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  WatchlistRoute: typeof WatchlistRoute
  TokenTokenIdRoute: typeof TokenTokenIdRoute
  ApiPublicOutcomeSamplerRoute: typeof ApiPublicOutcomeSamplerRoute
  ApiPublicProductionCycleTickRoute: typeof ApiPublicProductionCycleTickRoute
  ApiPublicThesisBenchmarkRoute: typeof ApiPublicThesisBenchmarkRoute
  ApiPublicThesisV2CalibrationRoute: typeof ApiPublicThesisV2CalibrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibration': {
      id: '/calibration'
      path: '/calibration'
      fullPath: '/calibration'
      preLoaderRoute: typeof CalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/calibration': {
      id: '/settings/calibration'
      path: '/calibration'
      fullPath: '/settings/calibration'
      preLoaderRoute: typeof SettingsCalibrationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/token/$tokenId': {
      id: '/token/$tokenId'
      path: '/token/$tokenId'
      fullPath: '/token/$tokenId'
      preLoaderRoute: typeof TokenTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/outcome-sampler': {
      id: '/api/public/outcome-sampler'
      path: '/api/public/outcome-sampler'
      fullPath: '/api/public/outcome-sampler'
      preLoaderRoute: typeof ApiPublicOutcomeSamplerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/production-cycle-tick': {
      id: '/api/public/production-cycle-tick'
      path: '/api/public/production-cycle-tick'
      fullPath: '/api/public/production-cycle-tick'
      preLoaderRoute: typeof ApiPublicProductionCycleTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/thesis-benchmark': {
      id: '/api/public/thesis-benchmark'
      path: '/api/public/thesis-benchmark'
      fullPath: '/api/public/thesis-benchmark'
      preLoaderRoute: typeof ApiPublicThesisBenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/thesis-v2-calibration': {
      id: '/api/public/thesis-v2-calibration'
      path: '/api/public/thesis-v2-calibration'
      fullPath: '/api/public/thesis-v2-calibration'
      preLoaderRoute: typeof ApiPublicThesisV2CalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsCalibrationRoute: typeof SettingsCalibrationRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCalibrationRoute: SettingsCalibrationRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalibrationRoute: CalibrationRoute,
  HistoryRoute: HistoryRoute,
  ResearchRoute: ResearchRoute,
  ScannerRoute: ScannerRoute,
  SettingsRoute: SettingsRouteWithChildren,
  WatchlistRoute: WatchlistRoute,
  TokenTokenIdRoute: TokenTokenIdRoute,
  ApiPublicOutcomeSamplerRoute: ApiPublicOutcomeSamplerRoute,
  ApiPublicProductionCycleTickRoute: ApiPublicProductionCycleTickRoute,
  ApiPublicThesisBenchmarkRoute: ApiPublicThesisBenchmarkRoute,
  ApiPublicThesisV2CalibrationRoute: ApiPublicThesisV2CalibrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
